[package]
name = "tide-workshop"
version = "0.1.0"
authors = ["Martin Asquino <martin.asquino@gmail.com> & Santiago Pastorino <spastorino@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
